// <auto-generated />
namespace NinjectWithEF.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class intialcreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intialcreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201409230407242_intial-create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
